unzip pm-plan-generator.zip
cd pm-plan-generator
git init
git add .
git commit -m "Initial commit: PM Plan Generator (Streamlit)"
git branch -M main
git remote add origin https://github.com/pbernarduk-design/pm-plan-generator.git
git push -u origin main

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
